<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
 <style>
   .footer {
   position: fixed;
   left: 0;
   bottom: 0;
   width: 100%;
   background-color: lightblue;
   color: white;
   text-align: center;
}
    </style>

</head>
<body background="C:\Users\barani mgmg\Desktop\Testing\Testing\termsandcondition.png">
<h1><center>Terms And Condition </center></h1>
<p style="font-family: times, serif; font-size:14pt; font-style:Cursive";>
<p align="justify">

SDL PLC ("SDL") AND ITS SUBSIDIARIES MAINTAIN THIS WEBSITE AS A SERVICE TO ITS CUSTOMERS, SHAREHOLDERS AND OTHER INTERESTED PARTIES. BY USING ANY WEBSITE OWNED AND OPERATED BY SDL PLC OR ITS AFFILIATES, YOU AGREE TO COMPLY WITH AND BE BOUND BY THE FOLLOWING TERMS OF USE, WHICH MAY CHANGE AT ANY TIME. IF YOU DO NOT AGREE TO THE TERMS AND CONDITIONS BELOW, PLEASE DO NOT USE THIS SITE OR ANY OF ITS PAGES.

USE OF MATERIALS ON THE SDL WEBSITE
ALL MATERIAL CONTAINED ON THE WEBSITE IS OWNED BY SDL PLC AND/OR ITS SUPPLIERS AND PROTECTED BY COPYRIGHT AND TRADEMARK LAWS. ANY MATERIAL MAY ALSO BE THE SUBJECT OF OTHER INTELLECTUAL PROPERTY RIGHTS OF SDL PLC AND/OR ITS SUPPLIERS ALL OF WHICH RIGHTS ARE RESERVED BY SDL PLC AND ITS SUPPLIERS.

NOTHING ON THE WEBSITE SHALL BE CONSTRUED AS CONFERRING ANY LICENSE UNDER SDL'S INTELLECTUAL PROPERTY RIGHTS, WHETHER BY IMPLICATION, ESTOPPEL OR OTHERWISE.

MATERIAL FROM THE SDL WEBSITE MAY BE PRINTED OR DOWNLOADED FOR YOUR OWN INFORMATIONAL, OR EDUCATIONAL PURPOSES ONLY, PROVIDED THAT YOU INCLUDE ALL COPYRIGHT AND PROPRIETARY NOTICES ORIGINALLY INCLUDED. YOU MAY NOT ATTEMPT TO "PASS-OFF" ANY OF THE MATERIAL AS YOUR OWN. YOU MAY NOT POST ON ANY OTHER WEBSITE, DISPLAY, OR DISTRIBUTE THE MATERIAL WITHOUT THE EXPRESS PRIOR WRITTEN CONSENT OF SDL.

COMPUTER SOFTWARE
ANY COMPUTER SOFTWARE WHICH MAY BE DOWNLOADED OR IS OTHERWISE AVAILABLE FROM THE WEBSITE IS LICENSED SUBJECT TO THE TERMS OF ITS ASSOCIATED LICENSE AGREEMENT ONLY, UNLESS EXPRESSLY STATED OTHERWISE. EXCEPT AS EXPRESSLY WARRANTED IN THE ASSOCIATED LICENSE AGREEMENT, SDL DISCLAIMS ALL WARRANTIES AND CONDITIONS WITH REGARD TO THE SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES AND CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.

THIRD PARTY MATERIALS ON THE SDL WEBSITE
THE WEBSITE MAY CONTAIN MATERIALS, INCLUDING SOFTWARE IN EXECUTABLE OR SOURCE CODE FORM, WHICH IS SUBMITTED BY THIRD PARTIES FOR INCLUSION ON THE SDL WEBSITE ("THIRD PARTY MATERIALS"). PLEASE BE ADVISED THAT SDL HAS NOT INDEPENDENTLY TESTED OR EVALUATED SUCH THIRD PARTY MATERIALS AND PROVIDES THEM ON THIS WEB SITE MERELY AS A SERVICE TO ITS USERS. ALL THIRD PARTY MATERIALS ON THE SDL WEBSITE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. TO THE MAXIMUM EXTENT PERMITTED BY LAW, SDL DISCLAIMS ALL LIABILITY FOR ANY CLAIMS, DEMANDS, SUITS OR ACTIONS, UNDER ANY THEORY OF LIABILITY, ARISING OUT OF THE USE OR ATTEMPTS TO USE SUCH THIRD PARTY MATERIALS.

SITES LINKED FROM THE SDL WEBSITE
THE SITES LINKED FROM THE WEBSITE ARE NOT UNDER SDL 'S CONTROL, AND SDL DOES NOT ASSUME ANY RESPONSIBILITY OR LIABILITY FOR ANY COMMUNICATIONS OR MATERIALS AVAILABLE AT SUCH LINKED SITES. SDL DOES NOT INTEND LINKS ON THE SDL WEBSITE TO BE REFERRALS OR ENDORSEMENTS OF THE LINKED ENTITIES, AND ARE PROVIDED FOR CONVENIENCE ONLY.

LIMITATION OF LIABILITY
UNDER NO CIRCUMSTANCES SHALL SDL BE LIABLE FOR ANY LOSSES OR DAMAGES WHATSOEVER, WHETHER IN CONTRACT, TORT OR OTHERWISE, FROM THE USE OF, OR RELIANCE ON, THE MATERIALS THAT MAKE UP THE WEBSITE. SDL SHALL NOT BE LIABLE FOR ANY LOSS HOWSOEVER ARISING, OR INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

SDL SHALL INCLUDE SDL PLC AND ITS DIVISIONS, SUBSIDIARIES, SUCCESSORS, PARENT COMPANIES, AND THEIR EMPLOYEES, PARTNERS PRINCIPALS, AGENTS AND REPRESENTATIVES, AND ANY THIRD-PARTY PROVIDERS OR SOURCES OF MATERIAL.

GOVERNING LAW
THESE TERMS AND CONDITIONS ARE GOVERNED BY AND TO BE CONSTRUED IN ACCORDANCE WITH ENGLISH LAW. ANY DISPUTES SHALL BE SUBJECT TO THE EXCLUSIVE JURISDICTION OF THE ENGLISH COURTS.
</font>
</p>
<!-- <form method="post" action="register.jsp" enctype=text/plain>
<table>
<INPUT TYPE="radio" name="command" value="0">I accept above terms and condition</input><BR>
<INPUT TYPE="radio" name="command" value="1">I do not accept above terms and condition</input>
</table>
  <p align="center">
 <input type="button" value="Agree Terms And Condition" onClick="location.href='register.jsp'">
 </p> -->
 <form action="register.jsp"   onsubmit="if(document.getElementById('agree').checked) { return true; } else { alert('Please indicate that you have read and agree to the Terms and Conditions and Privacy Policy'); return false; }">
 <br>
 <input type="checkbox" name="checkbox" value="check" id="agree" /> <b>I have read and agree to the Terms and Conditions and Privacy Policy</b>
<p align="center">
<input type="submit" name="submit" value="AGREE TERMS AND CONDITION" />
<footer class="container-fluid">
  <p align="center">CopyRight@baranikanshuu</p>
</footer>
</body>
</p>
<p>
<footer class="footer">
 <p align="center">CopyRight@baranikanshuu</p>
</footer>

</body>
</html>